[workspace]
resolver = "2"
members = ["ferrousdb", "crates/*"]

[workspace.package]
authors = ["mihir-l"]
edition = "2024"
rust-version = "1.86"
repository = "https://github.com/mihir-l/FerrousDB.git"

[workspace.dependencies]
